# Generated by Django 5.2.5 on 2025-08-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0002_user_can_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[("PayBill", "PayBill"), ("Cash", "Cash")],
                default="Cash",
                max_length=10,
            ),
        ),
    ]
