# Generated by Django 5.2.5 on 2025-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_stock",
            field=models.BooleanField(default=False),
        ),
    ]
