# Generated by Django 5.2.5 on 2025-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0004_remove_item_price_inventory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
